### ISSUE TITLE
Upgrade OASIS3-MCT version

### ISSUE THREAD

**Issue by nichannah** [COSIMA/oasis3-mct#5]
We are currently using OASIS3-MCT 2.0. There is a 3.0 version available. I think there are improvements which would be useful, e.g. support to couple multiple fields via a single communication

This is a duplicate of https://github.com/OceansAus/access-om2/issues/85

**Comment by aekiss** [comment]
Version 4.0 of OASIS3-MCT is now available: https://portal.enes.org/oasis/news/oasis3-mct_4-0-official-release

**Comment by nichannah** [comment]
The most interesting improvement looks like:
```
A new communication method, using the remapping weights to define the 
intermediate mapping decomposition, offering a significant gain at run time;
```

Hopefully moving from 2.0 to 4.0 provides a big enough performance gain to justify the work.

**Comment by nichannah** [comment]
Duplicate of https://github.com/COSIMA/access-om2/issues/85
